### PR TITLE
handle setting config dir in a better way

### PR DESCRIPTION
**Pull request by midiidev**
set the config dir using the `XDG_CONFIG_HOME` env var or fallback to `~/.config`, rather than explicitly using `/home/username/.config` to make the code function on less standard configurations.

### CODE REVIEW

**Comment by basicallygit** [comment]
Rust wont expand the  ~  if $XDG_CONFIG_HOME doesnt exist (it doesnt for me),

the check to detect if a config exist will instead look for a directory called '~' in the pwd,
and when it does not find it, create_dir_all() will create a directory called '~' e.g    "/home/user/Pictures/~/.config/....."

**Comment by midiidev** [comment]
latest commit should fix the issues you would have with it

**Review by basicallygit — APPROVED** [review]
👍 all good

**Review by electron271 — APPROVED** [review]
looks good

**Pull request merged**
