### PR TITLE
get a simple wm working

### PR DESCRIPTION
**Pull request by electron271**
todo:

- [x] app launcher
- [ ] small configuration possibilities
- [x] move windows around
- [x] resize windows

### CODE REVIEW

**Comment by a-weeb-programmer** [comment]
wtf, the checks stopped running for some reason

**Comment by a-weeb-programmer** [comment]
oh, it's because the files are in conflict

resolving now

**Comment by a-weeb-programmer** [comment]
welp, it did not work lmao

**Comment by electron271** [comment]
ready for review @a-weeb-programmer

**Comment by a-weeb-programmer** [comment]
poggies
reviewing now

**Review by a-weeb-programmer — APPROVED** [review]
we need more configurability, but we can work on that later.
We need to work on the udev stuff to be able to launch corrosionwm from a tty
other than that, it all looks good

**Comment by electron271** [comment]
i feel that should be done in a different pr for the udev

**Comment by a-weeb-programmer** [comment]
frik, not all commits were signed
time to bypass my own protection rules :trollface:

**Comment by electron271** [comment]
my bad lmao ill fix that later today

**Pull request merged**
