### PR TITLE
Drm backend

### PR DESCRIPTION
**Pull request by a-weeb-programmer**
So, progress is coming along quite nicely on the drm backend.
## Features:
   - [X] Scan for drm devices and handle any added or changed drm devices
   - [x] Handle removed drm devices
   - [x] Create rendering surface for the compositor
   - [x] Bind a render buffer to the multigpu renderer and have it draw the frames
   - [X] Scan for crtcs and connectors
   - [X] Create a software rendered compositor
   - [x] Create a hardware rendered compositor
   - [ ] Get the dmabuf feedback
   - [X] Creation of an egl device from a gbm device and have it get the render node
   - [x] Libinput backend
   - [ ] XWayland
   - [X] Create a global output
  
Once all of these features are completed, i will remove this pr from draft status

### CODE REVIEW

**Comment by a-weeb-programmer** [comment]
hardware compositor is now added

**Comment by a-weeb-programmer** [comment]
only 5 more tasks to go

**Comment by a-weeb-programmer** [comment]
also handles removed connectors now, but not removed devices. Will work on that next

**Comment by a-weeb-programmer** [comment]
another feature done

**Comment by a-weeb-programmer** [comment]
WOOOOOOOOOOOOOOOOOOOOOOOOO
YEAH BABYYYYYYYYYYYYYY

THAT'S WHAT I HAVE BEEN WAITING FOR
THAT'S WHAT IT'S ALL ABOUT

WOOOOOOOO

**Comment by Henry-Hiles** [comment]
Is xwayland working yet? Its unchecked in the features list at the top of this PR

**Comment by a-weeb-programmer** [comment]
all of the critical features of the backend are done. All that's left is dmabuf handling and xwayland support, but those features aren't essential, so the backend works now :D

**Comment by Henry-Hiles** [comment]
Great!

**Comment by electron271** [comment]
i will attempt running the code, and once CI passes i will approve

**Comment by a-weeb-programmer** [comment]
whaaa, you removed it from draft status? well, i was gonna complete xwayland and dmabuf handling, but if you really wanna merge, go ahead

**Comment by a-weeb-programmer** [comment]
I can't switch ttys for some reason(even though i completed the libinput backend), and programs can spawn, but windows won't really draw, but i think fixing that deserves its own branch since I'll have to make the custom render elements which will be a big change

**Comment by electron271** [comment]
we can do those in seperate pr

**Review by electron271 — APPROVED** [review]
checks have passed, and i ran the code and it works, i will merge

**Comment by a-weeb-programmer** [comment]
:D

WE FINALLY HAVE A BACKEND
HOLY CRAP THAT WAS A PAIN TO CODE

**Comment by basicallygit** [comment]
common corrosionwm  W

**Pull request merged**
